### ISSUE TITLE
Cannot run Polymer Doc

### ISSUE THREAD

**Issue by Robophil** [Polymer/docs#1327]
After building the doc with no error, when i run grunt i get the following

Running "concurrent:target1" (concurrent) task
Running "jekyll:serve" (jekyll) task
Running "vulcanize-elements" task
Running "compass:dist" (compass) task
Running "watch" task

Waiting...
Running "vulcanize:elements" (vulcanize) task
Running "appengine:run:frontend" (appengine) task
executing: dev_appserver.py --port=3000 --host=0.0.0.0 .  <=====localhost??
Fatal error: spawn dev_appserver.py ENOENT   <=========== error here
    Warning:  Use --force to continue.
        
        Aborted due to warnings.

is the host suppose to be 0.0.0.0 or localhost. If not how do i change that..

**Comment by arthurevans** [comment]
This error usually means that the script can't find dev_appserver.py. Try running just that command from the command line.

If you recently installed or updated the AppEngine package, you may need to run the GUI launcher once. You'll be prompted to create symlinks, which should fix the problem.

This happens every time app engine updates, unfortunately.

**Comment by Robophil** [comment]
how do i run the gui launcher. am on  ubuntu 14.0.4 LT

**Comment by arthurevans** [comment]
Sorry I missed this reply. Did you resolve this?

Steps may be different on Linux, which I haven't tried. You might not need the GUI launcher -- you may just need to set your PATH variable. I found the following online:

http://askubuntu.com/questions/123553/how-to-install-google-appengine

**Comment by Robophil** [comment]
i've not resolved this, but ill check out the link you put up

**Comment by arthurevans** [comment]
OK. If you still have problems, please update the bug here.

If I don't hear back in a week or so, I'll close out this bug.
